### ISSUE TITLE
GTM iframe displayed on Chrome (only) at localhost

### ISSUE THREAD

**Issue by gregorysimoes** [GorillaStack/meteor-iron-router-gtm#2]
We deployed meteor-iron-router-gtm in our dev environment (pointing at localhost) but we got an issue with the GTM manager iframe, which is displayed only on Google Chrome.

We also deployed it on our 'test' environment and the iframe isn't displayed, neither on Chrome, Firefox, Safari or IE.

How could we avoid the display of the iframe in dev environment - or is it normal that it doesn't appear on other browsers than Chrome?

Thanks!

![unnamed](https://cloud.githubusercontent.com/assets/8555313/10786611/6f2f5906-7d6b-11e5-9f32-a66c51d1ddf5.png)

**Comment by em0ney** [comment]
Hey there,

The iframe you speak of is the google tag manager preview pane.  It loads if preview mode is enabled for the environment you are in.  I'd recommend checking that tag manager is running in preview mode in your test environment.  It also only appears for users that are signed in to google tag manager (thus it won't show up in other browsers unless you sign in to tag manager in those browsers).

More info on using preview mode for tag manager here:
https://support.google.com/tagmanager/answer/6107056?hl=en

Thanks,
Elliott
